POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "11",
    "account_id_to": "22",
    "amount": 4600
}

###

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "22",
    "account_id_to": "11",
    "amount": 1000
}

###

GET http://localhost:3003/balances/11 HTTP/1.1

###

GET http://localhost:3003/balances/22 HTTP/1.1